language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t harrodtang/docker-react-2 -f Dockerfile.dev .

script:
  - docker run -e CI=true harrodtang/docker-react-2 npm run test
